spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: biblioteca
    password: biblioteca123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/biblioteca

server:
  port: 8080

